# git tag v1.0.0
# git push origin v1.0.0

name: Build and Release WPF EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore ./KoishiApp.csproj

      - name: Build project
        run: dotnet build ./KoishiApp.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./KoishiApp.csproj --configuration Release --output ./publish --no-restore
        
        # нужно чтобы всякое говно было в отдельной папке
      - name: Organize release files
        shell: pwsh
        run: |
          $libsFolder = "./publish/libs"
          if (-not (Test-Path $libsFolder)) {
              New-Item -ItemType Directory -Path $libsFolder | Out-Null
          }

          Get-ChildItem ./publish -Filter "*.dll" | ForEach-Object {
              Move-Item $_.FullName $libsFolder
          }
      - name: Archive release files
        run: Compress-Archive -Path ./publish/* -DestinationPath KoishiApp.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Релиз версии: ${{ github.ref_name }}
            По вопросам - **unicode1** (discord)
          files: KoishiApp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # changed from asd_2189sjcv89qjwdAknvy7j :troll:
