# git tag v1.0.0
# git push origin v1.0.0

name: Build and Release WPF EXE

on:
  push:
    tags:
      - 'v*' # см. первый коммент
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o publish

      - name: Get version
        id: get_version
        run: |
          $exePath = "publish/KoishiApp.exe"
          $versionInfo = (Get-Item $exePath).VersionInfo
          echo "VERSION=$($versionInfo.FileVersion)" >> $env:GITHUB_ENV

      - name: Package EXE
        run: |
          $zipName = "KoishiApp_v$env:VERSION.zip"
          cd publish
          Compress-Archive -Path "*.exe" -DestinationPath "../$zipName"
          cd ..
          echo "ZIP_PATH=$zipName" >> $env:GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Автоматический релиз версии ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENTOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
